### PR TITLE
Update variable.py to. use np.bool_ rather than deprecated np.bool

### PR DESCRIPTION
**Pull request by zm711**
NumPy versions >1.24 will no longer work with code including np.bool rather than issue a warning. So I just changed np.bool to np.bool_ which should work for new and older versions of NumPy.

### CODE REVIEW

**Comment by aepadilla4** [comment]
Hi @zm711! I don't have much experience with python. Would it be possible for you to share the steps on how to update the variable? I am having this same issue.

**Comment by aepadilla4** [comment]
@zm711 Thank you so much!

**Comment by Datamance** [comment]
#1193 Linking my issue so I know when this closes

**Comment by zm711** [comment]
@carsen-stringer I don't know when there would be a new pypi release. There are a couple other features that are also missing from the current pip install (#1167 for example helps with users of linux). So if you have users that plan to use linux install from the `.git` might still be the better option until/if a new pypi release is made. (also as of this writing there is an issue with python 3.12)

**Pull request merged**
