### PR TITLE
Add clustering facilities

### LINKED ISSUE #41: Selector
An object that represents a selection of spikes.

* Can be instanciated with `spike_clusters`
* Selection by specifying list of spikes or clusters (trait attributes)
* Support a maximum number of spikes, with automatic subselection performed if too many spikes are selected by the user
* Can be linked with a Reader: when the selection changes, new data may need to be fetched from disk or cache

See the [API](https://github.com/kwikteam/phy/wiki/API) on the wiki.

### LINKED ISSUE #42: Undo stack
* Start from the original clustering
* Save a stack of all actions: merge, custom spk->clu mapping (=split), move (ony forward actions are needed)
* Write an efficient function that applies a list of actions
* The undo/redo stack comes for free
* We can keep a limit to the history length: we save the complete mapping of the oldest item in the history, and apply further changes on it
* Benchmark: <50 ms to apply 100 successive changes on a 10M-long vector, if we keep in memory a tuple `(spike_changed, cluster)` (works for both merge and split; those are actually similar actions)

### LINKED ISSUE #45: ClusterManager class
A structure that handles:

* moving clusters into groups
* changing cluster colors
* relabelling clusters

### PR DESCRIPTION
**Pull request by rossant**
This PR adds a `phy.cluster.manual` package with most facilities needeed for manual sorting.
- The `Clustering` class keeps track of the spike --> cluster assignements.
- It implements `merge`, `assign`, and `split` methods.
- It comes with an undo stack based on cumulative diffs.
- The `ClusterMetadata` class holds information about each cluster (currently the cluster group and the color). It also implements an undo stack.
- The `GlobalHistory` implements a global undo stack that can handle multiple different stacks.
- `Clustering` and `ClusterMetadata` action methods return `UpdateInfo` objects that hold information about what spikes and clusters changed. This will be used by the global user-exposed controller to synchronize views and model.
- The `Selector` class allows one to select a number of spikes or clusters. A maximum number of spikes can be set: the subselection is done automatically.

Todo later:
- Limited undo stack (when len == 2N, checkpoint item N and delete the N oldest items)
- Better color support (random color when creating a new cluster)
- Relabelling

Closes #41, closes #42, closes #45.

### CODE REVIEW

**Comment by rossant** [comment]
@nippoo can you review this when you have time? thanks

**Comment by rossant** [comment]
If not yet reviewed, hold on @nippoo: I may add new stuff here.

**Comment by nippoo** [comment]
OK - tell me when. Nice coverage. (y)

**Comment by rossant** [comment]
OK @nippoo this naughty one is ready for review (assuming travis is happy).

**Pull request merged**
